version: 0.2

env:
  variables:
    TF_VERSION: "0.11.4"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"

  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - terraform version
#      - terraform init -no-color
#      - terraform plan -no-color
#      - terraform apply -no-color

  post_build:
    commands:
      - echo "terraform completed on `date`"

artifacts:
  files:
    - '**/*'
